# Generated by Django 6.0.3 on 2026-04-11 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_name_remove_employee_phone_number'),
        ('pumps', '0002_pump_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_pumps', to='employees.employee'),
        ),
    ]
