# Generated by Django 6.0.3 on 2026-04-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0003_pump_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pump',
            options={'ordering': ['pump_code']},
        ),
        migrations.AddField(
            model_name='pump',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pump',
            name='pump_code',
            field=models.CharField(default='PUMP-001', max_length=30),
            preserve_default=False,
        ),
    ]
