# Generated by Django 6.0.3 on 2026-04-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0004_alter_pump_options_pump_is_active_pump_pump_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='pump_code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
