# Generated by Django 6.0.3 on 2026-04-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0005_alter_pump_pump_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='pump_code',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
