# Generated by Django 6.0.3 on 2026-04-12 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_pointshistory_customer_and_more'),
        ('transactions', '0005_transaction_remaining_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointshistory',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='pointshistory',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pointshistory',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction'),
        ),
        migrations.AlterField(
            model_name='pointshistory',
            name='type',
            field=models.CharField(choices=[('earn', 'Earn'), ('redeem', 'Redeem'), ('adjustment', 'Adjustment')], max_length=20),
        ),
    ]
