# Generated by Django 6.0.3 on 2026-04-17 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_date_pointshistory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointshistory',
            name='customer_mobile',
            field=models.CharField(default=9876543219, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointshistory',
            name='customer_name',
            field=models.CharField(default='Rajesh', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pointshistory',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_history', to='customers.customer'),
        ),
    ]
