# Generated by Django 6.0.3 on 2026-04-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_pointshistory_customer_mobile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='pointshistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
