# Generated by Django 6.0.3 on 2026-04-29 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_options_alter_pointshistory_options_and_more'),
        ('transactions', '0007_alter_transaction_options_transaction_pump_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='total_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pointshistory',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pointshistory',
            name='customer_mobile',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='pointshistory',
            name='points_change',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pointshistory',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_history', to='transactions.transaction'),
        ),
    ]
