# Generated by Django 6.0.3 on 2026-04-29 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_total_points_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pointshistory',
            name='adjustment_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointshistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointshistory',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
    ]
