# Generated by Django 6.0.3 on 2026-04-29 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_pointshistory_adjustment_reason_and_more'),
        ('transactions', '0012_transaction_is_reversed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pointshistory',
            name='reversed_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_entry', to='customers.pointshistory'),
        ),
        migrations.AlterField(
            model_name='pointshistory',
            name='is_reversed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='pointshistory',
            name='type',
            field=models.CharField(choices=[('earn', 'Earn'), ('redeem', 'Redeem'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='pointshistory',
            index=models.Index(fields=['customer_mobile', 'created_at'], name='customers_p_custome_ce339f_idx'),
        ),
        migrations.AddIndex(
            model_name='pointshistory',
            index=models.Index(fields=['type', 'created_at'], name='customers_p_type_0f4be3_idx'),
        ),
    ]
