# Generated by Django 6.0.3 on 2026-04-29 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_pointshistory_reversed_entry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointshistory',
            name='reversed_entry',
        ),
        migrations.AddField(
            model_name='pointshistory',
            name='reversed_from',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal', to='customers.pointshistory'),
        ),
        migrations.AlterField(
            model_name='pointshistory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_history', to='customers.customer'),
        ),
    ]
