# Generated by Django 6.0.3 on 2026-04-29 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_remove_pointshistory_reversed_entry_and_more'),
        ('transactions', '0014_remove_transaction_reversed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointshistory',
            name='is_reversed',
        ),
        migrations.AddIndex(
            model_name='pointshistory',
            index=models.Index(fields=['transaction', 'created_at'], name='customers_p_transac_7a0e30_idx'),
        ),
        migrations.AddConstraint(
            model_name='pointshistory',
            constraint=models.UniqueConstraint(fields=('reversed_from',), name='unique_reversal_per_entry'),
        ),
    ]
