# Generated by Django 6.0.3 on 2026-04-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_remove_pointshistory_is_reversed_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pointshistory',
            name='unique_reversal_per_entry',
        ),
    ]
