# Generated by Django 6.0.3 on 2026-03-21 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pumps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel')], max_length=10)),
                ('price_per_litre', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pumps.pump')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('pump', 'fuel_type'), name='unique_pump_fuel')],
            },
        ),
    ]
