# Generated by Django 6.0.3 on 2026-03-21 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
        ('pumps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrate',
            name='pump',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_rates', to='pumps.pump'),
        ),
    ]
