# Generated by Django 6.0.3 on 2026-03-21 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
        ('pumps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('points_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pumps.pump')),
            ],
        ),
    ]
