# Generated by Django 6.0.3 on 2026-03-21 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_pointshistory_customer_and_more'),
        ('employees', '0002_alter_employee_pump_alter_employee_user'),
        ('pumps', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='attendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pump',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pumps.pump'),
        ),
    ]
