# Generated by Django 6.0.3 on 2026-04-12 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_name_remove_employee_phone_number'),
        ('transactions', '0003_rename_amount_transaction_final_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='attendant_name',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='attendant_phone',
            field=models.CharField(default='Unknown', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_mobile',
            field=models.CharField(default='Unknown', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_name',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_transactions', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='manager_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pump_location',
            field=models.CharField(default='Unknown', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='pump_name',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
    ]
