# Generated by Django 6.0.3 on 2026-04-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_attendant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='remaining_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
