# Generated by Django 6.0.3 on 2026-04-17 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_pointshistory_customer_mobile_and_more'),
        ('employees', '0003_remove_employee_name_remove_employee_phone_number'),
        ('pumps', '0003_pump_manager'),
        ('transactions', '0005_transaction_remaining_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='attendant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_transactions', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pump',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='pumps.pump'),
        ),
    ]
