# Generated by Django 6.0.3 on 2026-04-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_pointshistory_customer_mobile_and_more'),
        ('employees', '0004_employee_owner_alter_employee_pump'),
        ('pumps', '0005_alter_pump_pump_code'),
        ('transactions', '0006_alter_transaction_attendant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='pump_code',
            field=models.CharField(db_index=True, default='PUMP-001', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='attendant_phone',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer_mobile',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='manager_phone',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['pump_code', 'created_at'], name='transaction_pump_co_f15c38_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['attendant_phone', 'created_at'], name='transaction_attenda_ff1338_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['customer_mobile', 'created_at'], name='transaction_custome_5df70f_idx'),
        ),
    ]
