# Generated by Django 6.0.3 on 2026-04-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_total_points_and_more'),
        ('employees', '0006_alter_employee_unique_together'),
        ('pumps', '0006_alter_pump_pump_code'),
        ('transactions', '0007_alter_transaction_options_transaction_pump_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='points_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='points_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='remaining_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['pump_code'], name='transaction_pump_co_e883ce_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['fuel_type'], name='transaction_fuel_ty_82ff91_idx'),
        ),
    ]
