# Generated by Django 6.0.3 on 2026-04-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_total_points_and_more'),
        ('employees', '0006_alter_employee_unique_together'),
        ('pumps', '0006_alter_pump_pump_code'),
        ('transactions', '0008_alter_transaction_final_amount_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['fuel_type', 'created_at'], name='transaction_fuel_ty_5e2e27_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at', 'pump_code'], name='transaction_created_58172f_idx'),
        ),
    ]
