# Generated by Django 6.0.3 on 2026-04-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_transaction_transaction_fuel_ty_5e2e27_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_pump_co_e883ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_created_58172f_idx',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
