# Generated by Django 6.0.3 on 2026-04-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_remove_transaction_transaction_pump_co_e883ce_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_fuel_ty_82ff91_idx',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pump_code',
            field=models.CharField(max_length=30),
        ),
    ]
