# Generated by Django 6.0.3 on 2026-04-29 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_pointshistory_adjustment_reason_and_more'),
        ('employees', '0006_alter_employee_unique_together'),
        ('pumps', '0006_alter_pump_pump_code'),
        ('transactions', '0011_remove_transaction_transaction_fuel_ty_82ff91_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_reversed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reversed_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_entry', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('reversal', 'Reversal')], db_index=True, default='normal', max_length=10),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='transaction_transac_ed79fb_idx'),
        ),
    ]
