# Generated by Django 6.0.3 on 2026-04-29 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_transaction_reversed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='reversed_by',
        ),
    ]
