# Generated by Django 6.0.3 on 2026-04-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_remove_pointshistory_is_reversed_and_more'),
        ('employees', '0006_alter_employee_unique_together'),
        ('pumps', '0006_alter_pump_pump_code'),
        ('transactions', '0014_remove_transaction_reversed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='reversed_transaction',
            new_name='original_transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_reversed',
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['original_transaction'], name='transaction_origina_b738f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('original_transaction__isnull', True), ('transaction_type', 'normal')), models.Q(('original_transaction__isnull', False), ('transaction_type', 'reversal')), _connector='OR'), name='valid_transaction_reversal_structure'),
        ),
    ]
